# Autogenerated wrapper script for GAP_pkg_cddinterface_jll for aarch64-linux-musl
export CddInterface

using GAP_jll
using GMP_jll
using cddlib_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_cddinterface")
JLLWrappers.@declare_file_product(CddInterface)
function __init__()
    JLLWrappers.@generate_init_header(GAP_jll, GMP_jll, cddlib_jll)
    JLLWrappers.@init_file_product(
        CddInterface,
        "lib/gap/CddInterface.so",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
